### ISSUE TITLE
[Request] Quell EvenniaCode Bot's URL preview on Discord.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evdemo#4]
#### Issue
On Discord, URLs are previewed by default. Meaning that a giant chunk of the chat gets hogged up by the EvenniaCode Bot sending links to IRC, which are then forwarded to Discord.

Here's an example of what it looks like in the Discord chat.
https://i.imgur.com/gkqRe7O.png

#### Suggested change
Discord will quell the preview behavior if a URL is encapsulated within <>

My suggestion is to change the EvenniaCode Bot's default behavior so that links are now surrounded with <> 

Here's an example of how links should look on the EvenniaCode Bot: 
`<https://github.com/evennia/evennia/wiki/EvMenu>`

There is a feature within Discord to disable the automatic link previewing, but the preview is on by default and so the behavior will continue for those not aware of how to turn it off. https://i.imgur.com/op25GSM.png

***

The community has weighed in on this request and the majority of them have agreed that this is the best course of action.
https://i.imgur.com/kSZI0lY.png

**Comment by kovitikus** [comment]
Apparently the bot can be specifically targeted to turn off previews on Discord, so this issue is now solved.

**Comment by kovitikus** [comment]
Guess I was wrong. This wasn't able to be resolved. In any case, even if the Discord admins do manage to fix it somehow, might as well get at the source and fix it there for certainty's sake.

**Comment by Griatch** [comment]
Fixed at the evenniacode-bot level.
