### ISSUE TITLE
[BUG] evenniacode bot no longer properly quells Discord URL previews.

### ISSUE THREAD

**Issue by kovitikus** [evennia/evdemo#5]
As is evidenced by this screenshot, the previews are no longer quelled. #4
![screenshot](https://i.imgur.com/VZC10Ac.png)

The current format of the URL link is:
```
(<__https://github.com/evennia/evennia/issues/2452__>) 
```

I don't know if Discord made changes to the parser or if the double underscores were added to the code bot and broke it, but the only way the preview will quell now is if the < > are directly up against the URL itself.
```
(__<https://github.com/evennia/evennia/issues/2452>__) 
```

On a side note, the URL doesn't function properly with the `<__ __>` format.
But it does become a proper URL when the `__< >__` format is used.

**Comment by Griatch** [comment]
It appears discord stopped understanding IRC underscore markers. Removed them now to appease you sensitive people in discord :wink:
